services:
  flask:
    image: gestion_academica:1.0
    restart: always
    networks:
      - mired
    env_file:
      - .env
    environment:
      - FLASK_CONTEXT=production
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      - CACHE_TYPE=${CACHE_TYPE}
      - CACHE_REDIS_HOST=${CACHE_REDIS_HOST}
      - CACHE_REDIS_PORT=${CACHE_REDIS_PORT}
      - CACHE_REDIS_DB=${CACHE_REDIS_DB}
      - SECRET_KEY=${SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`backend.universidad.localhost`)"
      #- "traefik.http.routers.flask.tls=true"
      - "traefik.http.routers.flask.entrypoints=web"
      #- "traefik.http.routers.flask.middlewares=flask-retry,flask-cb"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
      - "traefik.docker.network=mired"
      #- "traefik.http.middlewares.flask-retry.retry.attempts=3"
      #- "traefik.http.middlewares.flask-retry.retry.initialinterval=100ms"
      #- "traefik.http.middlewares.flask-cb.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - mired
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    networks:
      - mired
    volumes:
      - redisdata:/data
    ports:
      - "6380:6379"

networks:
  mired:
    external: true

volumes:
  pgdata:
  redisdata: