services:
  flask:
    build: .
    image: gestion_academica
    container_name: flask-sysacad
    restart: always
    networks:
      - mired
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Flask
      - FLASK_CONTEXT=production
      # SQLAlchemy
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      # Redis Cache
      - CACHE_TYPE=${CACHE_TYPE}
      - CACHE_REDIS_HOST=${CACHE_REDIS_HOST}
      - CACHE_REDIS_PORT=${CACHE_REDIS_PORT}
      - CACHE_REDIS_DB=${CACHE_REDIS_DB}
      - CACHE_REDIS_PASSWORD=${CACHE_REDIS_PASSWORD}
      # Hashids
      - HASHIDS_MIN_LENGTH=${HASHIDS_MIN_LENGTH}
      - HASHIDS_ALPHABET=${HASHIDS_ALPHABET}
      - HASHIDS_SALT=${HASHIDS_SALT}
      # Seguridad
      - SECRET_KEY=${SECRET_KEY}
    labels:
      - "traefik.enable=true"
      # ROUTER 
      - "traefik.http.routers.backend.rule=Host(`backend.universidad.localhost`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.middlewares=backend-retry,backend-cb"
      # SERVICE 
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.docker.network=mired"
      # RETRY 
      - "traefik.http.middlewares.backend-retry.retry.attempts=3"
      - "traefik.http.middlewares.backend-retry.retry.initialinterval=100ms"
      # CIRCUIT BREAKER
      - "traefik.http.middlewares.backend-cb.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
networks:
  mired:
    external: true
